def checkpw():
    pmsg.set('請輸入密碼:'+ppw.get())
import tkinter as tk
win = tk.Tk()
win.geometry('400x300')
win.title('分析程式')
frame1 = tk.Frame(win)
frame1.pack(padx=20,pady=10)
ppw = tk.StringVar()
pmsg = tk.StringVar()
pLabel = tk.Label(frame1,text='請輸入密碼')
pLabel.pack()
pEntry = tk.Entry(frame1,textvariable=ppw)
pEntry.pack()
frame2 = tk.Frame(win,bg='blue')
frame2.pack(padx=20,pady=10)
pButton=tk.Button(frame2,text='登入',command=checkpw)
pButton.pack()
pLabmsg = tk.Label(frame2,textvariable=pmsg)
pLabmsg.pack()
win.mainloop()